### ISSUE TITLE
Kirkstone support

### ISSUE THREAD

**Issue by BennyBread** [ni/meta-security#4]
HI, is ist possible to add support for kirkstone branch?

**Comment by amstewart** [comment]
Hey @BennyBread,

We're currently working on a release of NI LinuxRT which supports the [hardknott](https://github.com/ni/meta-security/tree/nilrt/master/hardknott)-compat version of this repo. It's a substantial effort to rebase the whole of the NILRT platform to a new yocto release. So at the moment, upgrading our meta-layers to a new base is a long-term commitment. I'm not yet able to say what yocto release we will choose as the next base after hardknott - but Kirkstone is a good candidate, since it is an LTS release.

It also seems like `kirkstone` support [was only added](https://git.yoctoproject.org/meta-security/commit/conf/layer.conf?id=30a4227e3c5b47005dedb3f89299d933557b9209) in the meta-security upstream `master` ref in late-February, and upstream doesn't yet have a stable branch for kirkstone. For layers like meta-security - where there is active upstream yocto maintainership - we prefer to wait for a stable branch before adopting the base.

Is there something in the meta-security master ref that you need? If you have a compelling case, we might consider backporting the functionality to hardknott.

**Comment by amstewart** [comment]
I'm going to close this issue, as it hasn't seen any action in several months. Feel free to file a new issue. if you have a specific request.
